version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podemaster_app
    ports:
      - "8000:8000"
    volumes:
      - app_data:/app/data
    environment:
      - ENV=production

  db:
    image: postgres:13
    container_name: podemaster_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: podemaster
    volumes:
      - db_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: podemaster_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  app_data:
  db_data: