# .github/workflows/ci.yml

name: Continuous Integration

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  # This triggers CI on pull requests as well

jobs:
  test:
    runs-on: ubuntu-latest  # This runs the workflow on a Linux environment
  
    services:
        # Use Docker service to run the API container
        api:
          image: ghcr.io/omiidos/cc24-podemaster:latest 
          ports:
            - 8000:8000  # Expose port 8000 from the container to the host 
  
  

    steps:
    # Step 1: Check out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  
    
    

    # Step 3: Install dependencies
    - name: Install dependencies
      run: make install
    # Step 4: Set PYTHONPATH to fix ModuleNotFoundError
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV
    
    # Step 4: Run tests using pytest
    - name: Run tests
      run: make test

   
